image: gitlab/dind:local
before_script:
  - echo $LOCAL_CI_REGISTRY
  - 'docker login $LOCAL_CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD'

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'docker build -t $LOCAL_CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_REF_NAME .'
    - docker push $LOCAL_CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_TAG
  only:
    - tags
    - dev
  tags:
    - python_build

deploy:
  stage: deploy
  script:
    - docker pull $LOCAL_CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_TAG
    - 'docker ps -a | grep cmdbdeploy && docker stop cmdbdeploy && docker rm cmdbdeploy'
    - docker run  -d --restart always --name cmdbdeploy -p 80:8000 $LOCAL_CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_TAG
  environment:
    name: production
    url: http://192.168.100.236/clonevm
  after_script:
    - date
  only:
    - tags
  dependencies:
    - build
  tags:
    - deploy_236_shell
