before_script:
  - echo $CI_REGISTRY
  - 'docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD'

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - 'docker build -t $CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_REF_NAME .'
    - docker push $CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_TAG
  only:
    - tags
  tags:
    - deploy_236_shell
  cache:
    paths:
      - ./.cache/

deploy:
  stage: deploy
  script:
    - 'docker ps -a | grep cmdbdeploy && docker stop cmdbdeploy && docker rm cmdbdeploy'
    - docker run -it -d --name cmdbdeploy -p 80:8000 $CI_REGISTRY/cmdb/cmdb:$CI_COMMIT_TAG
  environment:
    name: production
    url: http://192.168.100.236/adddisk
  after_script:
    - date
  only:
    - tags
  dependencies:
    - build
  tags:
    - deploy_236_shell
